<?php

/**
 * @Author: Sholi
 * @Date:   2022-11-26 18:50:31
 * @Last Modified by:   Sholi
 * @Website: sholi.co
 * @Email: info@sholi.co
 * @Last Modified time: 2022-11-26 18:50:31
 */


?>

<h3 style="text-align: center; margin-top: 10px;">Generated by <a target="_blank" href="https://wordpress.org/plugins/sholi-url-shortener/">Sholi URL Shortener</a></h3>